#!/usr/bin/env bash
# Stub generator: writes a single draft file for testing
mkdir -p content/drafts || true
cat > content/drafts/0001-autogen.md <<'MD'
---
title: "Autogen Draft"
date: "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
tags: [autogen, test]
---

This is an autogenerated draft for testing the pipeline.
MD

echo "WROTE content/drafts/0001-autogen.md"
