#!/usr/bin/env bash
# Generate and verify a draft. If CLAUDE_API_KEY is set, this script should call Claude Opus 4.6 APIs.
# For now, if CLAUDE_API_KEY is missing, create a realistic stub draft and a verification note.
set -euo pipefail
OUT_DIR=content/published
DRAFT_DIR=content/drafts
AUDIT_DIR=audit
mkdir -p "$OUT_DIR" "$DRAFT_DIR" "$AUDIT_DIR"
TIMESTAMP=$(date -u +%Y%m%dT%H%M%SZ)
SLUG="autogen-${TIMESTAMP}"
TITLE="Autogen: Story of Jazz ${TIMESTAMP}"
FILENAME="$OUT_DIR/${TIMESTAMP}-${SLUG}.md"
AUDIT_PATH="$AUDIT_DIR/${SLUG}"
mkdir -p "$AUDIT_PATH"
if [ -n "${CLAUDE_API_KEY-}" ]; then
  # Placeholder for real Claude API call
  # e.g., call an API, pass prompt from specs/prompt_spec.md, get content + sources + verification
  echo "[PLACEHOLDER] Would call Claude Opus 4.6 here with prompt from specs/prompt_spec.md" > "$AUDIT_PATH/prompt.txt"
  echo "[PLACEHOLDER] Raw model output would be saved here." > "$AUDIT_PATH/raw_output.txt"
  # Fake content for now
  BODY="This is a generated draft about an aspect of jazz history. (Real generation would use Claude Opus 4.6.)"
  SOURCES=("https://en.wikipedia.org/wiki/Jazz" "https://www.britannica.com/art/jazz")
  CONFIDENCE=0.80
  VERIFY_NOTE="Automatic verification placeholder: sources fetched and basic checks passed."
else
  # Stub path (no external API keys)
  echo "No CLAUDE_API_KEY found — using stub generator." > "$AUDIT_PATH/prompt.txt"
  echo "Stub generation: short sample content." > "$AUDIT_PATH/raw_output.txt"
  BODY="This is a STUB draft generated locally for testing the pipeline."
  SOURCES=("https://en.wikipedia.org/wiki/Jazz" "https://www.britannica.com/art/jazz")
  CONFIDENCE=0.80
  VERIFY_NOTE="Stub verification: accepted for staging."
fi
cat > "$FILENAME" <<MD
---
title: "$TITLE"
date: "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
slug: "$SLUG"
tags: [autogen]
sources:
MD
for s in "${SOURCES[@]}"; do
  echo "  - \"$s\"" >> "$FILENAME"
done
cat >> "$FILENAME" <<MD
---

$BODY
MD
# Save audit info
echo "$TITLE" > "$AUDIT_PATH/title.txt"
echo "$CONFIDENCE" > "$AUDIT_PATH/confidence.txt"
echo "$VERIFY_NOTE" > "$AUDIT_PATH/verify_note.txt"
# Commit results
git add "$FILENAME" "$AUDIT_PATH" || true
git commit -m "chore: add autogenerated draft $SLUG" || true
# push branch
export GIT_ASKPASS=echo
git push https://${GITHUB_PAT}@github.com/OliDevBot/HistoryOfJazz.git develop || true

echo "WROTE $FILENAME"
echo "AUDIT -> $AUDIT_PATH"
